# Generated by Django 4.0.1 on 2022-01-27 16:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('rollno', models.IntegerField(default=0)),
                ('hostel', models.CharField(choices=[('Hostel A', 'Hostel A'), ('Hostel B', 'Hostel B'), ('Hostel C', 'Hostel C'), ('Hostel D', 'Hostel D'), ('Hostel E', 'Hostel E'), ('Hostel F', 'Hostel F'), ('Hostel G', 'Hostel G'), ('Hostel H', 'Hostel H'), ('Hostel I', 'Hostel I'), ('Hostel J', 'Hostel J'), ('Hostel K', 'Hostel K'), ('Hostel L', 'Hostel L'), ('Hostel M', 'Hostel M'), ('Hostel N', 'Hostel N'), ('Hostel O', 'Hostel O')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(default='Absent', max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
