# Generated by Django 4.0.2 on 2022-04-12 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentvideo',
            old_name='photo',
            new_name='video',
        ),
    ]
