# Generated by Django 4.0.2 on 2022-02-21 16:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 21, 16, 2, 41, 72074, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 2, 21, 16, 2, 41, 72125, tzinfo=utc)),
        ),
    ]
