# Generated by Django 4.0.2 on 2022-04-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
