# Generated by Django 4.0.2 on 2022-03-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_attendance_date_alter_attendance_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], max_length=200),
        ),
    ]
