# Generated by Django 4.0.2 on 2022-03-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_outside',
            field=models.BooleanField(default=False),
        ),
    ]
