# Generated by Django 4.0.2 on 2022-03-13 08:12

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_studentphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentphoto',
            name='photo',
            field=models.ImageField(upload_to=users.models.photo_upload_path),
        ),
        migrations.AlterField(
            model_name='studentphoto',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='users.student'),
        ),
    ]
