# Generated by Django 4.0.2 on 2022-03-15 11:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_studentphoto_photo_alter_studentphoto_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentphoto',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
